version: '3.6'

services:
  test:
    image: plebeianmarket-api
    depends_on:
      api:
        condition: service_healthy
    environment:
      - ENV=test
      - DEBUG=1
      - DB_USERNAME=
      - DB_PASSWORD=
      - FLASK_APP=main
      - BASE_URL=http://api:5000
    volumes:
      - "./api:/app"
    networks:
      - proxy
    command: flask run-tests
