version: '3.6'

services:
  db:
    build:
      context: ./
      dockerfile: ./services/postgres/Dockerfile
    networks:
      - db_network
  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    environment:
      - APP=api
    image: plebeianmarket-api
    depends_on: [db]
    restart: on-failure
    stop_grace_period: 1m
    networks:
      - db_network
      - proxy
  finalize-auctions:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    image: plebeianmarket-api
    depends_on: [db]
    restart: on-failure
    stop_grace_period: 1m
    networks:
      - db_network
  settle-btc-payments:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    image: plebeianmarket-api
    depends_on: [db]
    restart: on-failure
    stop_grace_period: 1m
    networks:
      - db_network
  lightning-payments-processor:
    build:
      context: ./
      dockerfile: ./ln_payments_processor/Dockerfile
    image: plebeianmarket-ln-payments
    depends_on: [db]
    restart: on-failure
    stop_grace_period: 30s
    networks:
      - db_network
  birdwatcher:
    build:
      context: ./
      dockerfile: ./birdwatcher/Dockerfile
    image: plebeianmarket-birdwatcher
    restart: on-failure
    stop_grace_period: 15s
    networks:
      - db_network
networks:
  db_network:
    driver: bridge
  proxy:
    driver: bridge
