version: '3.6'

services:
  api:
    environment:
      - BASE_URL=https://plebeian.market
      - LND_GRPC=plebeian-market.m.voltageapp.io:10009
  nginx:
    environment:
      - VIRTUAL_HOST=plebeian.market
      - LETSENCRYPT_HOST=plebeian.market
  settle-bids:
    environment:
      - FLASK_APP=main
      - LND_GRPC=plebeian-market.m.voltageapp.io:10009
