version: '3.6'

services:
  api:
    environment:
      - ENV=prod
      - BASE_URL=https://plebeian.market
      - LND_GRPC=plebeian-market.m.voltageapp.io:10009
      - S3_FILENAME_PREFIX=P_
      - MODERATOR_USER_IDS=1,5
      - LOG_LEVEL=INFO
  nginx:
    environment:
      - VIRTUAL_HOST=plebeian.market
      - LETSENCRYPT_HOST=plebeian.market
  settle-btc-payments:
    environment:
      - FLASK_APP=main
      - LOG_LEVEL=INFO
  settle-lnd-payments:
    environment:
      - FLASK_APP=main
      - LND_GRPC=plebeian-market.m.voltageapp.io:10009
      - LOG_LEVEL=INFO
  process-notifications:
    environment:
      - FLASK_APP=main
      - LOG_LEVEL=INFO
