version: '3.6'

services:
  web:
    build:
      context: ./
      dockerfile: web/backoffice/Dockerfile
      args:
        - BUILD_MODE=-production
  api:
    healthcheck:
      test: ["CMD", "curl", "-f", "https://plebeian.market/api/healthcheck"]
      interval: 3s
      timeout: 3s
      retries: 5
    env_file: .env.prod
    environment:
      - S3_FILENAME_PREFIX=P_
      - MODERATOR_USER_IDS=1,5,328
  nginx:
    environment:
      - VIRTUAL_HOST=plebeian.market
      - LETSENCRYPT_HOST=plebeian.market
  finalize-auctions:
    env_file: .env.prod
  settle-btc-payments:
    env_file: .env.prod
  process-notifications:
    env_file: .env.prod
  birdwatcher:
    env_file: .env.prod
